//  Each new term in the Fibonacci sequence is generated by adding the previous two
// terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

fn fibonacci(n: u64) -> u64 {
    match n {
        0 => 0,
        1 | 2 => 1,
        3 => 2,
        _ => fibonacci(n - 1) + fibonacci(n - 2),
    }
}

fn main() {
    let mut total = 0u64;
    for f in (0..).map(|x| fibonacci(x)) {
        if f > 4000000 {
            break;
        } else if f % 2 == 0 {
            total += f;
        }
    }
    println!("Result: {:?}", total);
}
